export const FETCH_TEMPERATURES = 'FETCH_TEMPERATURES';
export const FETCH_TEMPERATURES_SUCCESS = 'FETCH_TEMPERATURES_SUCCESS';
export const FETCH_TEMPERATURES_FAILURE = 'FETCH_TEMPERATURES_FAILURE';
export const TO_CELSIUS_TEMPERATURES = 'TO_CELSIUS_TEMPERATURES';
export const TO_FAHRENHEIT_TEMPERATURES = 'TO_FAHRENHEIT_TEMPERATURES';
export const SET_SELECTED_TEMPERATURE_DAY = 'SET_SELECTED_TEMPERATURE_DAY';